services:
  3cx-zammad-bridge:
    build: .
    container_name: 3cx-zammad-bridge
    restart: always
    volumes:
      - ./config.yaml:/etc/zammadbridge/config.yaml
    networks:
      - zammad_default

networks:
  zammad_default:
    external: true
